name: Release nik

on:
  push:
    tags:
      - "v*"

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x

      - name: Compile nik
        run: deno task build

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: nik
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
